import time
print("WELCOME TO THE PYTHON BANK MANAGEMENT SYSTEM"          )
time.sleep(2)
print("Select your role")
time.sleep(0.5)
print("1) Banker")
print("2) Customer")
print()
print("3) Exit")
time.sleep(2)
print("Choose your role :")
